/**/

//WORDCLOCK_UTILS_H
#ifndef WORDCLOCK_UTILS_H
#define WORDCLOCK_UTILS_H

  #define WIFI_SSID "YOUR SSID"
  #define WIFI_PASS "YOUR PASS"
  #define HOSTNAME  "WordClock"

#endif

/* 
   Helper for juggling around charachters. 
   Top row LEDs runs from left to right, second from right to left (backwards),
   third row LEDs runs from left to right, fourth from right to left (backwards), etc.

   FWD12-BCKWD12-FWD12-BCKWD12-FWD12-BCKWD12-FWD12-BCKWD12-FWD12-BCKWD12-
   FWD12-BCKWD12-FWD12-BCKWD12-FWD12-BCKWD12-FWD12-BCKWD12-FWD12-BCKWD12

!.aS.ISCHO.sLETREIV.DLABZWEISFuFACHTaNuNFLoWZFLESaCHSIEBa..@GIZNAWZaNHaZHALBI.VOR.ABITHCA.IFLoWZDruFuFiZaHNI.IREIV.SIEWZSaCHSIEBNI.#321.ISG.IFLE
aSZISCHQ####LETREIVJDLABZWEISFuFACHTFLoWZXFLEuRDSaCHSIEBaZaHKGIZNAWZaNuNHALBI#VORVABITHCABIFLoWZDRuFuFIZaHNIWIREIVYSIEWZSaCHSIEBNIG#ISGPINuNIFLE

/*  LED/pixel IDs
 * 
 *      012345678901
 *   0--ÄSZISCHQ####---11 <- Sun/Moon/NTP/WiFi
 *  23--BALDJVIERTEL---12
 *  24--ZWEISFÜFACHT---35
 *  47--DRÜELF#ZWoLF---36 <- X = 41 = Xmas
 *  48--SÄCHSIEBÄZÄH---59
 *  71--NÜNÄZWANZIGK---60
 *  72--VORAB#VHALBI---83 <- heart
 *  95--ZWÖLFIBACHTI---84
 *  96--DRÜFÜFIZÄHNI--107 
 * 119--ZWEIS#VIERIW--108 <- # = 114 = Easter
 * 120--SaCHSIEBNIG#--131
 * 143--ELFINÜNIPGSI--132
 *      012345678901  */
